title: S-LAB
description: Statistical Learning Across Biomedicine
url: "https://vic-dragon.github.io"
baseurl: ""
theme: null

plugins:
  - jekyll-seo-tag

markdown: kramdown
permalink: pretty

collections:
  pages:
    output: true
    permalink: /:path/

include:
  - _pages
